version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - docker-service

  node-app:
    build:
      context: .
    container_name: node-app
    ports:
      - "8000:8000"
    networks:
      - docker-service
    depends_on:
      - postgres
    restart: always

networks:
  docker-service:
    driver: bridge
